In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3,4,5])
b=np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [7]:
type(a)

numpy.ndarray

In [8]:
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [9]:
#Creating 2d array
a2=np.array([[1,2,3,],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [11]:
#Creating 3d array
a3 = np.array([[[1,2,3],[4,5,6]],
            [[7,8,9]],[[10,11,12]],
            [[13,14,15],[16,17,18]]],)
print(a3)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [19]:
#Creating 3d array
a3=np.array([[[1,2,3],[4,5,6]],
            [[7,8,9]],[[10,11,12]],
            [[13,14,15],[16,17,18]]])
print(a3)
type(a3)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [18]:
print(a2.shape)
print(a3.shape)

(2, 3)


NameError: name 'a3' is not defined

In [19]:
print(a2.ndim)

2


In [20]:
print(a2.dtype)

int32


In [25]:
np.arange(11)
np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [31]:
np.random.randint(1,11, size=(2,3))

array([[10,  4,  2],
       [ 2,  2,  5]])

In [32]:
np.random.randint(1,11, size=(3,2,3))


array([[[ 5, 10,  2],
        [ 6,  6,  9]],

       [[ 6,  7,  9],
        [ 9,  5,  6]],

       [[ 8,  7,  8],
        [ 7,  6, 10]]])

In [13]:
x= np.random.randint(1,21, size=(2,2))
y= np.random.randint(1,21, size=(2,2))
print(x)
print(y)

[[10 15]
 [12 15]]
[[19 17]
 [ 3  3]]


In [11]:
print(x+y)
print(x-y)
print(x*y)

[[35 16]
 [29 30]]
[[-1  6]
 [ 9 -4]]
[[306  55]
 [190 221]]


In [12]:
#1st method
print(x@y)

NameError: name 'x' is not defined

In [13]:
#2nd method
np.dot(x,y)

array([[416, 272],
       [472, 316]])

In [11]:
x.prod()

NameError: name 'x' is not defined

In [18]:
x.mean()
y.mean()

12.5

In [14]:
b= x.mean(axis=0)  #column wise
print(b)

[11. 15.]


In [21]:
c=x.mean(axis=1) #row wise
print(c)

[14. 16.]


In [15]:
print(x.sum())
print(x.std())
print(x.var())

52
2.1213203435596424
4.5


In [16]:
arr=np.array([1,2,3,4,5,6])
print(np.percentile(arr,50))
print(np.percentile(arr,25))
print(np.percentile(arr,75))

3.5
2.25
4.75


In [17]:
arr2 = np.random.randint(11,100,(4,4))
print(arr2)

[[19 80 72 28]
 [73 44 64 77]
 [24 18 42 41]
 [55 90 52 99]]


In [31]:
print('2x8')
print(arr2.reshape(2,8))
print('8x2')
print(arr2.reshape(8,2))

2x8
[[23 13 12 55 85 18 90 63]
 [70 30 32 62 93 73 42 48]]
8x2
[[23 13]
 [12 55]
 [85 18]
 [90 63]
 [70 30]
 [32 62]
 [93 73]
 [42 48]]


In [18]:
print(arr2)

[[19 80 72 28]
 [73 44 64 77]
 [24 18 42 41]
 [55 90 52 99]]


In [23]:
print(arr[0]) #0th row
print(arr2[0,1]) #0th row 1st column
print(arr2[-1])  #last row
print(arr2[:3])
print(arr2[1:])

1
80
[55 90 52 99]
[[19 80 72 28]
 [73 44 64 77]
 [24 18 42 41]]
[[73 44 64 77]
 [24 18 42 41]
 [55 90 52 99]]


In [24]:
arr2 > 50

array([[False,  True,  True, False],
       [ True, False,  True,  True],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [39]:
y = arr2[arr2>50]
z= y.reshape(5,5)
print(z)


ValueError: cannot reshape array of size 9 into shape (5,5)

In [1]:
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'