In [8]:
import numpy as np

In [9]:
a=np.array([1,2,3,4,5])
b=np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [4]:
type(a)

numpy.ndarray

In [5]:
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [6]:
#Creating 2d array
a2=np.array([[1,2,3,],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [11]:
#Creating 3d array
a3 = np.array([[[1,2,3],[4,5,6]],
            [[7,8,9]],[[10,11,12]],
            [[13,14,15],[16,17,18]]],)
print(a3)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [19]:
#Creating 3d array
a3=np.array([[[1,2,3],[4,5,6]],
            [[7,8,9]],[[10,11,12]],
            [[13,14,15],[16,17,18]]])
print(a3)
type(a3)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [18]:
print(a2.shape)
print(a3.shape)

(2, 3)


NameError: name 'a3' is not defined

In [19]:
print(a2.ndim)

2


In [20]:
print(a2.dtype)

int32


In [25]:
np.arange(11)
np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [31]:
np.random.randint(1,11, size=(2,3))

array([[10,  4,  2],
       [ 2,  2,  5]])

In [32]:
np.random.randint(1,11, size=(3,2,3))


array([[[ 5, 10,  2],
        [ 6,  6,  9]],

       [[ 6,  7,  9],
        [ 9,  5,  6]],

       [[ 8,  7,  8],
        [ 7,  6, 10]]])

In [10]:
x= np.random.randint(1,21, size=(2,2))
y= np.random.randint(1,21, size=(2,2))
print(x)
print(y)

[[17 11]
 [19 13]]
[[18  5]
 [10 17]]


In [11]:
print(x+y)
print(x-y)
print(x*y)

[[35 16]
 [29 30]]
[[-1  6]
 [ 9 -4]]
[[306  55]
 [190 221]]


In [12]:
#1st method
print(x@y)

[[416 272]
 [472 316]]


In [13]:
#2nd method
np.dot(x,y)

array([[416, 272],
       [472, 316]])

In [14]:
x.prod()

46189

In [18]:
x.mean()
y.mean()

12.5

In [20]:
b= x.mean(axis=0)  #column wise
print(b)

[18. 12.]


In [21]:
c=x.mean(axis=1) #row wise
print(c)

[14. 16.]


In [23]:
print(x.sum())
print(x.std())
print(x.var())

60
3.1622776601683795
10.0


In [27]:
arr=np.array([1,2,3,4,5,6])
print(np.percentile(arr,50))
print(np.percentile(arr,25))
print(np.percentile(arr,75))

3.5
2.25
4.75


In [28]:
arr2 = np.random.randint(11,100,(4,4))
print(arr2)

[[23 13 12 55]
 [85 18 90 63]
 [70 30 32 62]
 [93 73 42 48]]


In [31]:
print('2x8')
print(arr2.reshape(2,8))
print('8x2')
print(arr2.reshape(8,2))

2x8
[[23 13 12 55 85 18 90 63]
 [70 30 32 62 93 73 42 48]]
8x2
[[23 13]
 [12 55]
 [85 18]
 [90 63]
 [70 30]
 [32 62]
 [93 73]
 [42 48]]
